CREATE TABLE BOARD(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CELL00VALUE INT,
  CELL01VALUE INT,
  CELL02VALUE INT,
  CELL03VALUE INT,
  CELL10VALUE INT,
  CELL11VALUE INT,
  CELL12VALUE INT,
  CELL13VALUE INT,
  CELL20VALUE INT,
  CELL21VALUE INT,
  CELL22VALUE INT,
  CELL23VALUE INT,
  CELL30VALUE INT,
  CELL31VALUE INT,
  CELL32VALUE INT,
  CELL33VALUE INT
);